# Generated by Django 4.2.3 on 2023-07-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='uploadDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
