# Generated by Django 4.2.3 on 2023-08-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='user',
            new_name='commenter',
        ),
    ]
