# Generated by Django 4.2.3 on 2023-07-25 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userProfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_photo', models.ImageField(default='', upload_to='user/images/')),
                ('bio', models.TextField(default='')),
                ('registration_date', models.DateField()),
                ('last_login_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
