# Generated by Django 4.2.3 on 2023-07-31 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Followers', '0001_initial'),
        ('Messaging', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='follow_det',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Followers.follow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=10),
        ),
    ]
