# Generated by Django 4.2.3 on 2023-08-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0005_alter_message_timestamp_alter_room_follow_det'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
    ]
