# Generated by Django 4.2.3 on 2023-07-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='Accounts.userprofile')),
                ('following', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='Accounts.userprofile')),
            ],
        ),
    ]
